### ISSUE TITLE
webpack require undefined when used alongside NamedModulesPlugin

### ISSUE THREAD

**Issue by Connorelsea** [mastilver/dynamic-cdn-webpack-plugin#29]
I am getting this error when attempting to integrate this into my webpack config. I am using this webpack config: https://github.com/Connorelsea/react-typescript-starter/blob/master/webpack.prod.js

![image](https://user-images.githubusercontent.com/1844458/29682836-14027184-88d2-11e7-86ee-beb3d3040bec.png)

**Comment by mastilver** [comment]
Yep managed to reproduced it, I will try to find what's the issue here

Let me know if you find where it's coming from!

**Comment by mastilver** [comment]
Looks like it's caused by `NamedModulesPlugin`, which is weird because I'm using it as well on my project without any issue :/

**Comment by Connorelsea** [comment]
What version of NamedModulesPlugin/webpack are you using and what order should it be included in?

**Comment by mastilver** [comment]
I'm using webpack@2 and it doesn't have to do with the order

I've got a failing test, I'm now trying to find where it's coming from :)

**Comment by mastilver** [comment]
So yeah, this issue is only happening on webpack@3

**Comment by mastilver** [comment]
Released in 3.4.0

**Comment by Connorelsea** [comment]
This fixed it for me. Thanks a ton! @mastilver

**Comment by Connorelsea** [comment]
Getting a 98 in performance on light house using this in my build

![image](https://user-images.githubusercontent.com/1844458/29690421-89627b44-88ec-11e7-966f-01bbc6067d28.png)

**Comment by mastilver** [comment]
@Connorelsea Which is better or worst?

Depends on the context but the majority of the time, the first visit is slower than not using this plugin
But on the long term, it becomes handy as your dependencies don't update as much as your code, so your users won't need to re-download your dependencies again and again
