### ISSUE TITLE
Resolving modules called from an external folder

### ISSUE THREAD

**Issue by alfonsogarciacaro** [mastilver/dynamic-cdn-webpack-plugin#36]
Hi there! First of all, thanks a lot for this great plugin. I just started it and I'm impressed with the results but I have only little problem. I use it for [Fable](http://fable.io/) projects, a compiler from F# to JS. Because Fable is compatible with Webpack, we can import directly F# files into the bundle. However F# dependencies, unlike npm, are being downloaded to a cache folder that it's not in the project directory. Because of this when one of the modules that I want to change to CDN (say "react-dom") is being imported not from the project code, but from one of the dependencies, the `contextPath` will be an external folder and the call to `resolvePkg` in the following line fails:

https://github.com/mastilver/dynamic-cdn-webpack-plugin/blob/aa5792785d41076bf03dc02fe1550a7e095fb6a7/src/index.js#L81

To avoid this kind of problems I add the following to webpack.config.js:

```js
  resolve: {
    modules: [path.join(__dirname, "./node_modules/")]
  },
```

Thanks to this, loaders can use `this.resolve` ([reference](https://webpack.github.io/docs/how-to-write-a-loader.html#resolve-dependencies)) to locate modules even from folders external to the project. But apparently this function is not available for plugins or at least I couldn't find it.

I managed to fix the issue by capturing the `compiler.context` (e.g. `this.originalContext = compiler.context`) here:

https://github.com/mastilver/dynamic-cdn-webpack-plugin/blob/aa5792785d41076bf03dc02fe1550a7e095fb6a7/src/index.js#L49-L50

And then using it instead of `contextPath` in the line mentioned above. So my question is: would it be OK to send a PR to make an extra flag available (say `options.useOriginalContext`) and use the `compiler.context` instead of `contextPath` when this flag is activated?

**Comment by MangelMaxime** [comment]
Hello guys, any news on this issue ?

**Comment by mastilver** [comment]
Hi

I don't think the proposed solution is the right one (please prove me wrong)

So maybe I didn't understand correctly but without `dynamic-cdn-webpack-plugin` you don't need to do anything to make your project work, right?
So my assumption is that if it's working with webpack, it should work with this plugin out of the box without the need for a flag

**Comment by mastilver** [comment]
But tbh, right now I'm very confused by this, I think a test would clarify things a lot (using js not fable)

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for your reply @mastilver. We have solved it on our side, so we can close this :)
