### ISSUE TITLE
Babel Example

### ISSUE THREAD

**Issue by djstein** [mastilver/dynamic-cdn-webpack-plugin#38]
Hey! Great work, saw this at a talk today from https://twitter.com/swyx at ReactNYC meetup.

Can we add Babel / ES6 syntax for installation:
```
import DynamicCdnWebpackPlugin from 'dynamic-cdn-webpack-plugin'

  plugins: [
     ...,
    new DynamicCdnWebpackPlugin()
  ]
```
I'm having my server run fine, but it is not building with expected values

**Comment by mastilver** [comment]
The above code should work... Can you tell me what's going wrong?
