### ISSUE TITLE
Cleanup before v4 release

### ISSUE THREAD

**Issue by mastilver** [mastilver/dynamic-cdn-webpack-plugin#40]
- [x] update ava
- [ ] ~use native js (no build step / babel)~
- [ ] double check there is no references to pre webpack 4
  - [ ] src
  - [ ] test

**Comment by aulisius** [comment]
Can we get started on this? I have some free time this week and I was thinking we can wrap this up.

**Comment by mastilver** [comment]
@aulisius Yeah sorry, working on it right now

I think we are going do keep babel for now, I don't want to deal with async/await. We should be able to remove it after node 6 EOL (next April)

**Comment by mastilver** [comment]
Now I just need to use webpack new mode instead of NODE_ENV for prod of dev urls, and we will be ready for release

@aulisius Do you want to have a quick look if we need to do anything else?

**Comment by mastilver** [comment]
v4 is out, @aulisius Thank you for the help! :)
