### ISSUE TITLE
doesn't parse other libraries

### ISSUE THREAD

**Issue by geoshar** [mastilver/dynamic-cdn-webpack-plugin#45]
It parses only jquery, or some other libraries like react maybe, but it doesn't include all the libraries on the node_modules for example
import Clipboard from 'clipboard';
so, how to solve this?

**Comment by aulisius** [comment]
Hey :)

You'd have to create a PR and add the appropriate JS file links here:  https://github.com/mastilver/module-to-cdn

**Comment by geoshar** [comment]
Thanks!
i've inserted like this:

moduleToCdn('video.js', '6.6.0',{
    env: 'production'
});

i don't see a link on manifest.json, only jquery goes

**Comment by mastilver** [comment]
This is the file you need to update: https://github.com/mastilver/module-to-cdn/blob/master/modules.json

Because every module is different, we need to configure it for each modules

**Comment by geoshar** [comment]
Hey Thanks! I've looked into this, and created another way to do a similar thing, without manifest.json, and no modules.json needed, just a 5kb autoloader.js which will load everything, depending on what you included into this. [autoloader-cdn](https://github.com/geoshar/autoloader-cdn)
