### ISSUE TITLE
99.9% of my packages could not be found, but they exist in CDN

### ISSUE THREAD

**Issue by rendomnet** [mastilver/dynamic-cdn-webpack-plugin#56]
Is this suppose to be like this? 
only plugin that was replaced by cdn was react-router-dom

❌ 'lodash' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json

but 
https://unpkg.com/lodash@4.17.11/ exists

 'redux-form' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'dayjs' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ '@babel/runtime/helpers/inherits' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ '@babel/runtime/helpers/getPrototypeOf' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ '@babel/runtime/helpers/possibleConstructorReturn' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ '@babel/runtime/helpers/createClass' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'eventemitter3' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'prop-types' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'scriptjs' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ '@mapbox/point-geometry' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/core-js/object/get-prototype-of' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/classCallCheck' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/createClass' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/possibleConstructorReturn' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/inherits' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'react-lifecycles-compat' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'prop-types' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/extends' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/core-js/object/get-prototype-of' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/classCallCheck' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/createClass' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/possibleConstructorReturn' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/inherits' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'prop-types' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/core-js/object/keys' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/classCallCheck' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/createClass' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/possibleConstructorReturn' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/core-js/object/get-prototype-of' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/inherits' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'prop-types' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/objectWithoutProperties' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/extends' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/core-js/object/get-prototype-of' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/createClass' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/possibleConstructorReturn' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/inherits' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'react-lifecycles-compat' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'prop-types' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/classCallCheck' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/extends' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/core-js/object/get-own-property-descriptor' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
❌ 'babel-runtime/helpers/classCallCheck' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json
....

**Comment by aulisius** [comment]
Hey @rendomnet,

Thanks for filing the issue. This plugin uses [mastilver/module-to-cdn](https://github.com/mastilver/module-to-cdn/blob/master/modules.json) to find out if the CDN version of a module exists.

In this case, these libraries should exist in [this json file](https://github.com/mastilver/module-to-cdn/blob/master/modules.json).

If you're interested, you can create a PR to add these to that file.

Hope that helps,
@aulisius.

**Comment by PatchRanger** [comment]
@rendomnet I had the same issue. For everyone who came here from web-search, here is my recipe which works like a charm for me: I've added custom unpkg-based resolver to `webpack.config.js`, see below.
```js
plugins: [
        new DynamicCdnWebpackPlugin({
            verbose: true,
            resolver: (packageName, packageVersion, options) => {
                return {
                    name: packageName.replace('@', ''),
                    var: packageName.replace('@', ''),
                    version: packageVersion,
                    url: `https://unpkg.com/${packageName}@${packageVersion}`,
                };
            },
        }),
],
```
And that's the output (well, piece of):
```
> "node_modules/.bin/webpack" --mode=production
✔️ 'accounting' will be served by https://unpkg.com/accounting@0.4.1
✔️ 'jquery' will be served by https://unpkg.com/jquery@3.4.1
✔️ 'jquery-ui/ui/widgets/progressbar' will be served by https://unpkg.com/jquery-ui/ui/widgets/progressbar@1.12.1
✔️ 'shopify/app-bridge-utils' will be served by https://unpkg.com/@shopify/app-bridge-utils@1.28.0
✔️ 'url-search-params-polyfill' will be served by https://unpkg.com/url-search-params-polyfill@8.1.0
✔️ 'shopify/app-bridge' will be served by https://unpkg.com/@shopify/app-bridge@1.28.0
✔️ 'sentry/browser' will be served by https://unpkg.com/@sentry/browser@5.22.3
✔️ 'sentry/integrations' will be served by https://unpkg.com/@sentry/integrations@5.11.1
...
```
And here's the content of `manifest.json`:
```
  "accounting.1": "https://unpkg.com/accounting@0.4.1",
  "jquery.1": "https://unpkg.com/jquery@3.4.1",
  "jquery-ui/ui/widgets/progressbar.1": "https://unpkg.com/jquery-ui/ui/widgets/progressbar@1.12.1",
  "@shopify/app-bridge-utils.0": "https://unpkg.com/@shopify/app-bridge-utils@1.28.0",
  "url-search-params-polyfill.0": "https://unpkg.com/url-search-params-polyfill@8.1.0",
  "@shopify/app-bridge.0": "https://unpkg.com/@shopify/app-bridge@1.28.0",
  "@sentry/browser.3": "https://unpkg.com/@sentry/browser@5.22.3",
  "@sentry/integrations.1": "https://unpkg.com/@sentry/integrations@5.11.1"
```
Don't know why there are numeric postfixes - but it looks working, I don't mind)
Hope it helps.
