### ISSUE TITLE
Optional and peer dependencies

### ISSUE THREAD

**Issue by sultan99** [mastilver/dynamic-cdn-webpack-plugin#61]
I'm making a  [library ](https://github.com/sultan99/react-on-lambda) that have optional and peer dependencies.

The end-users (developers) of my library may optionally install package `styled-components` or not.
But  `dynamic-cdn-webpack` plugin always injects the optional package in the index.html, even it was not installed!

My library `package.json` has section `optionalDependencies` , so there is a way how to know which is optional and peer dependency.

Here is a [project](https://github.com/sultan99/rol-vs-jsx/tree/master/rol) to produce the bug:
```sh
git clone git@github.com:sultan99/rol-vs-jsx.git
cd rol-vs-jsx
npm i
npm run build
```
After build check folder `dist/rol`. If you open **index.html** you will find it includes script with `styled-components` which should not be because the package is not used in the project.

![image](https://user-images.githubusercontent.com/2598056/55680626-d866be80-593d-11e9-8e09-a96379726bbd.png)

Can you fix the bug?

**Comment by aulisius** [comment]
Hey @sultan99,

So, I believe the library's current implementation of dealing with peer dependencies is what works well for most libraries. A peer dependency isn't optional and it shouldn't be treated as such.

If you were to remove `styled-components` from `peerDependencies`, I think the output would be as you expect it to be.

**Comment by sultan99** [comment]
Hi @aulisius!
When I remove the styled-components from peerDependencies, then it breaks when I install the styled-components in the parent project:
![image](https://user-images.githubusercontent.com/2598056/55687622-db3ecf00-5990-11e9-9475-b2c6bda845c3.png)

You can check this version https://unpkg.com/react-on-lambda@0.3.9/dist/react-on-lambda.min.js built without the package in peerDependencies:
![image](https://user-images.githubusercontent.com/2598056/55687642-222cc480-5991-11e9-8b7a-54aae2f63a4c.png)

**Comment by sultan99** [comment]
This [project](https://github.com/sultan99/rol-usage) uses styled-component if install react-on-lambda v0.3.9 then it stops to work.

**Comment by aulisius** [comment]
@sultan99, I was able to run the above mentioned project successfully with `react-on-lambda@0.3.9`.

```sh
$ npm ls styled-components
rol-usage@0.1.0 /Developer/rol-usage
├─┬ react-on-lambda@0.3.9
│ └── styled-components@4.2.0  deduped
└── styled-components@4.2.0
```

<img width="1680" alt="Screen Shot 2019-04-08 at 6 13 28 AM" src="https://user-images.githubusercontent.com/6629172/55692426-76ea3280-59c5-11e9-929b-4ee1672b60c5.png">

**Comment by sultan99** [comment]
I don't know why I get the error 🤔...

My environment:
- win10
- npm 6.9.0 (tried on 6.8.0 same issue)
- node v11.10.0

![image](https://user-images.githubusercontent.com/2598056/55698874-d4907600-59e9-11e9-8955-3a9971cefe97.png)

**Comment by sultan99** [comment]
I have checked it on another PC, worked!
Looks I have some issue with that computer.

Anyway, @aulisius thank you for helping and I close this issue.

**Comment by aulisius** [comment]
@sultan99, maybe you can try removing the `package-lock.json` file and see if it helps.
